### ISSUE TITLE
Still good to use?

### ISSUE THREAD

**Issue by githubforced2fabad** [Bike/sandalphon.lambda-list#2]
Is this library still good to use or is there a better option?

**Comment by Bike** [comment]
I would not use it. Alternatives include alexandria's `parse-ordinary-lambda-list`, [Ecclesia](https://github.com/s-expressionists/Ecclesia)'s various lambda list parsers, and the parsers in [CST](https://github.com/s-expressionists/Concrete-syntax-tree).

**Comment by githubforced2fabad** [comment]
My memory serves me correct then since I remember you saying something like that before. Anyway, in the time before you responded here, I started this project https://git.sr.ht/~charje/lambda-list which uses modular mixins for parsing different lambda list parts. I didn't know Ecciesia existed, but neither it nor CST look very customizable to me (also using `:none` instead of `nil` seems ick to me).

Thanks for responding here. Might I suggest to archive this project so that people can tell not use it.

**Comment by Bike** [comment]
CST also uses mixins, but okay. Archiving this project is a good idea, I will do that.
